# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose
# values do not exceed four million, find the sum of the even-valued terms.

ans = 0
list1 = [1, 1]
while True:
    next = list1[0] + list1[1]
    
    if next > 4000000:
        break
    
    if next % 2 == 0:
        ans += next

    if list1[0] < list1[1]:
        list1[0] = next
    
    elif list1[1] < list1[0]:
        list1[1] = next

    else:
        list1[1] = next

print(ans)

